// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xussfezfrnmorpfouslg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1c3NmZXpmcm5tb3JwZm91c2xnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNjUyMTksImV4cCI6MjA3MDc0MTIxOX0.BDCatXuX3UIcb0sUNwRrZ4AI2-kLxNDEIOWMx99WgOg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});